### ISSUE TITLE
Small issue

### ISSUE THREAD

**Issue by jgrisham4** [pointwise/GridRefine#1]
First off, thank you for this script.  It comes in very handy.  It would be nice if this was implemented as a feature in Pointwise.  I'm using the script to perform an h-refinement on a single structured block and found that the script failed.  The issue is at line 729.  The unset unsSolver should be moved inside the foreach brackets.  If we don't have any unstructured blocks, unsSolver is never defined in the procedure so we are trying to unset something that was never set.  

Thanks,

James

**Comment by traviscarrigan** [comment]
James,

Thank you for bringing this to our attention. I just pushed a fix to the main branch. 

Travis
