### ISSUE TITLE
gridRefine doesn't redimension TRex

### ISSUE THREAD

**Issue by eszwabow** [pointwise/GridRefine#2]
First off, this is a fantastic script that saved me tons of time on a mesh-refinement study!

I did notice a small bug though, in the getAndRedimensionTRexCondition process, line 142 always fails to check if the boundary condition is "Wall" since it calls getType instead of getConditionType.

I changed it to:
**if { [$condition _getConditionType_] eq "Wall" } {**

and it works.

Thanks again for the awesome script.

Eddie

**Comment by traviscarrigan** [comment]
Eddie,

Thank you for the catch! I've updated the script using the correct "getConditionType" function. 

Travis
